# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('votes', models.IntegerField()),
            ],
        ),
    ]
