# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='movie_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
